version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y libpq-dev libzip-dev php-pgsql
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - composer install
      - npm install

  build:
    commands:
      - npm run build
      - php artisan migrate --force
artifacts:
  files:
    - '**/*'
  discard-paths: no